# Generated by Django 3.1.2 on 2021-08-29 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='projects.person')),
            ],
            options={
                'ordering': ('person', '-expiry'),
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['person', '-expiry'], name='users_sessi_person__629f9f_idx'),
        ),
    ]
