# Generated by Django 3.1.2 on 2021-08-29 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=999)),
                ('public_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('private_key', models.UUIDField(default=uuid.uuid4)),
                ('plan_type', models.CharField(default='basic', max_length=1000)),
                ('subscription_id', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('apply_plan', models.BooleanField(default=False)),
                ('monthly_payment', models.PositiveIntegerField(default=0)),
                ('monthly_users', models.PositiveIntegerField(default=25)),
                ('message_history', models.PositiveIntegerField(default=14)),
                ('upgrade_reminder_date_time', models.DateTimeField(blank=True, null=True)),
                ('is_emails_enabled', models.BooleanField(default=False)),
                ('email_company_name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('email_sender', models.EmailField(blank=True, default='', max_length=255, null=True)),
                ('email_link', models.URLField(blank=True, default='', max_length=500, null=True)),
                ('email_last_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('owner', 'public_key'),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=999)),
                ('secret', models.CharField(max_length=999)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('custom_json', jsonfield.fields.JSONField(default=dict)),
                ('is_online', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=True, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(db_column='public_key', on_delete=django.db.models.deletion.CASCADE, related_name='people', to='projects.project')),
            ],
            options={
                'ordering': ('project', 'username'),
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='projects.person')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['public_key'], name='projects_pr_public__d3091e_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['private_key'], name='projects_pr_private_fb61cb_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['project', 'username'], name='projects_pe_public__0521ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('project', 'username')},
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['id'], name='projects_co_id_dd3ab1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('id',)},
        ),
    ]
