# Generated by Django 3.1.2 on 2021-09-04 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20210904_0246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collaboraotor',
            new_name='Collaborator',
        ),
        migrations.RemoveIndex(
            model_name='collaborator',
            name='projects_co_email_322689_idx',
        ),
        migrations.AddIndex(
            model_name='collaborator',
            index=models.Index(fields=['user', 'project'], name='projects_co_email_5f55f0_idx'),
        ),
    ]
