# Generated by Django 3.1.2 on 2021-09-04 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20210904_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('access_key', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(db_column='public_key', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='projects.project')),
                ('user', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('project', 'user'),
            },
        ),
        migrations.AddIndex(
            model_name='invite',
            index=models.Index(fields=['project', 'user'], name='projects_in_public__8effd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('project', 'user')},
        ),
    ]
