# Generated by Django 3.1.2 on 2021-09-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210906_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'ordering': ('project', 'to_email')},
        ),
        migrations.RemoveIndex(
            model_name='invite',
            name='projects_in_public__8effd2_idx',
        ),
        migrations.AddField(
            model_name='invite',
            name='to_email',
            field=models.EmailField(default='', max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('project', 'to_email')},
        ),
        migrations.AddIndex(
            model_name='invite',
            index=models.Index(fields=['project', 'to_email'], name='projects_in_public__4814ec_idx'),
        ),
        migrations.RemoveField(
            model_name='invite',
            name='user',
        ),
    ]
