# Generated by Django 3.1.2 on 2021-09-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210906_2036'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invite',
            index=models.Index(fields=['access_key'], name='projects_in_access__c3c095_idx'),
        ),
    ]
