# Generated by Django 3.1.2 on 2021-09-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210907_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='to_email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
