# Generated by Django 3.1.2 on 2021-10-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210910_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='goal',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
