version: "3.6"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8000:8080"
    environment:
      - PIPELINE=local
      - REDIS_HOST=redis
      - AWS_STORAGE_BUCKET_NAME=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - SEND_GRID_KEY=
    command: daphne -b 0.0.0.0 -p 8080 server.asgi:application
  redis:
    image: "redis:alpine"