# Generated by Django 3.1.2 on 2021-10-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created', 'email'], name='accounts_us_created_9e6b71_idx'),
        ),
    ]
